const sampleActivities2 = [
  {
    title: "Cricket Match at Stadium",
    description: "A thrilling T20 match between local teams.",
    location: "Eden Gardens, Kolkata",
    date: new Date("2025-06-10"),
    time: "17:00",
    category: "cricket",
  },
  {
    title: "Movie Night: Inception",
    description: "Watch Christopher Nolan's masterpiece in 4K.",
    location: "PVR Cinemas, Mumbai",
    date: new Date("2025-06-12"),
    time: "19:30",
    category: "movies",
  },
  {
    title: "Football Tournament Finals",
    description: "Final match of the local football championship.",
    location: "Salt Lake Stadium, Kolkata",
    date: new Date("2025-06-15"),
    time: "20:00",
    category: "football",
  },
  {
    title: "Open Air Movie: Interstellar",
    description: "Experience cinema under the stars.",
    location: "Lodhi Garden, Delhi",
    date: new Date("2025-06-18"),
    time: "18:45",
    category: "movies",
  },
  {
    title: "Cricket Workshop for Beginners",
    description: "Learn basics of cricket from experienced coaches.",
    location: "Chinnaswamy Stadium, Bangalore",
    date: new Date("2025-06-20"),
    time: "10:00",
    category: "cricket",
  },
  {
    title: "Cricket Match: India vs Australia",
    description: "A thrilling ODI match between India and Australia.",
    location: "Wankhede Stadium, Mumbai",
    date: new Date("2025-06-10"),
    time: "15:00",
    category: "cricket",
  },
  {
    title: "Movie Night: Interstellar",
    description: "Experience Nolan's sci-fi classic on the big screen.",
    location: "INOX, Delhi",
    date: new Date("2025-06-11"),
    time: "19:00",
    category: "movies",
  },
  {
    title: "Football Match: Local League Finals",
    description: "Final showdown between the top two football clubs.",
    location: "Salt Lake Stadium, Kolkata",
    date: new Date("2025-06-12"),
    time: "20:30",
    category: "football",
  },
  {
    title: "Cricket Training Camp",
    description: "Intensive training camp for cricket lovers.",
    location: "M. Chinnaswamy Stadium, Bangalore",
    date: new Date("2025-06-13"),
    time: "08:00",
    category: "cricket",
  },
  {
    title: "Movie Marathon: Marvel Series",
    description: "Back-to-back Marvel movies in one go.",
    location: "PVR Phoenix Mall, Pune",
    date: new Date("2025-06-14"),
    time: "16:00",
    category: "movies",
  },
  {
    title: "Friendly Football Match",
    description: "A fun game for all football enthusiasts.",
    location: "Nehru Stadium, Chennai",
    date: new Date("2025-06-15"),
    time: "17:00",
    category: "football",
  },
  {
    title: "Movie Night: Sholay Remastered",
    description: "Classic Indian movie experience with modern audio-visuals.",
    location: "Raj Mandir, Jaipur",
    date: new Date("2025-06-16"),
    time: "18:30",
    category: "movies",
  },
  {
    title: "Under-19 Cricket Match",
    description: "Watch the stars of tomorrow in action.",
    location: "Green Park Stadium, Kanpur",
    date: new Date("2025-06-17"),
    time: "14:00",
    category: "cricket",
  },
  {
    title: "Football Screening: Euro Finals",
    description: "Watch the Euro finals with a crowd of fans.",
    location: "Open Grounds, Hyderabad",
    date: new Date("2025-06-18"),
    time: "21:00",
    category: "football",
  },
  {
    title: "Outdoor Movie: Zindagi Na Milegi Dobara",
    description: "Outdoor movie screening under the stars.",
    location: "Cubbon Park, Bangalore",
    date: new Date("2025-06-19"),
    time: "19:30",
    category: "movies",
  },
  {
    title: "Charity Football Match",
    description: "Support a good cause through sports.",
    location: "Cooperage Ground, Mumbai",
    date: new Date("2025-06-20"),
    time: "18:00",
    category: "football",
  },
  {
    title: "Night Cricket Tournament",
    description: "Exciting night matches with local teams.",
    location: "Sawai Mansingh Stadium, Jaipur",
    date: new Date("2025-06-21"),
    time: "20:00",
    category: "cricket",
  },
  {
    title: "Documentary Movie: The Game Changers",
    description: "A documentary about athletes on plant-based diets.",
    location: "Alliance Francaise, Delhi",
    date: new Date("2025-06-22"),
    time: "17:30",
    category: "movies",
  },
  {
    title: "Women’s Football Match",
    description: "Watch rising stars of women's football in action.",
    location: "Jawaharlal Nehru Stadium, Kochi",
    date: new Date("2025-06-23"),
    time: "16:30",
    category: "football",
  },
  {
    title: "Celebrity Cricket League",
    description: "Celebrities playing cricket for entertainment.",
    location: "DY Patil Stadium, Navi Mumbai",
    date: new Date("2025-06-24"),
    time: "19:00",
    category: "cricket",
  },
  {
    title: "T20 Cricket Match: India vs Pakistan",
    description: "An exciting T20 match between India and Pakistan.",
    location: "Dubai International Stadium, Dubai",
    date: new Date("2025-06-25"),
    time: "20:00",
    category: "cricket",
  },
  {
    title: "Movie Premiere: Avatar 2",
    description: "Join the premiere of the highly anticipated movie.",
    location: "Cinemax, Mumbai",
    date: new Date("2025-06-26"),
    time: "19:00",
    category: "movies",
  },
  {
    title: "Football Match: Real Madrid vs Barcelona",
    description:
      "The El Clasico, one of the biggest football rivalries in the world.",
    location: "Santiago Bernabéu Stadium, Madrid",
    date: new Date("2025-06-27"),
    time: "22:00",
    category: "football",
  },
  {
    title: "Cricket Training Session",
    description:
      "Join this session for tips and tricks on improving your cricket skills.",
    location: "MCA Ground, Pune",
    date: new Date("2025-06-28"),
    time: "10:00",
    category: "cricket",
  },
  {
    title: "Movie Screening: The Dark Knight",
    description: "Watch the legendary Batman movie on the big screen again.",
    location: "Big Cinemas, Kolkata",
    date: new Date("2025-06-29"),
    time: "20:30",
    category: "movies",
  },
  {
    title: "Football Friendly: Arsenal vs Chelsea",
    description:
      "Watch this exciting friendly match between Arsenal and Chelsea.",
    location: "Emirates Stadium, London",
    date: new Date("2025-07-01"),
    time: "19:00",
    category: "football",
  },
  {
    title: "Cricket Legends Meetup",
    description: "Meet the legends of Indian cricket and hear their stories.",
    location: "National Sports Club of India, Mumbai",
    date: new Date("2025-07-02"),
    time: "16:00",
    category: "cricket",
  },
  {
    title: "Movie Screening: The Pursuit of Happyness",
    description: "Inspiring movie screening about overcoming life’s obstacles.",
    location: "Gold Cinema, Pune",
    date: new Date("2025-07-03"),
    time: "18:00",
    category: "movies",
  },
  {
    title: "Football Match: Juventus vs AC Milan",
    description: "A classic Serie A football match.",
    location: "Allianz Stadium, Turin",
    date: new Date("2025-07-04"),
    time: "22:30",
    category: "football",
  },
  {
    title: "Cricket Charity Match",
    description:
      "Participate and watch a charity cricket match for a good cause.",
    location: "Feroz Shah Kotla Ground, Delhi",
    date: new Date("2025-07-05"),
    time: "15:00",
    category: "cricket",
  },
  {
    title: "Movie Screening: The Lion King",
    description: "Relive the magic of The Lion King with a special screening.",
    location: "Sathyam Cinemas, Chennai",
    date: new Date("2025-07-06"),
    time: "17:00",
    category: "movies",
  },
  {
    title: "Football League: Junior Championship",
    description: "A junior football league for budding players.",
    location: "Football Stadium, Chandigarh",
    date: new Date("2025-07-07"),
    time: "10:00",
    category: "football",
  },
  {
    title: "Cricket Women's Tournament",
    description: "An exciting women’s cricket tournament featuring top teams.",
    location: "Eden Gardens, Kolkata",
    date: new Date("2025-07-08"),
    time: "14:00",
    category: "cricket",
  },
  {
    title: "Movie Night: Joker",
    description: "Watch the dark and thrilling movie Joker.",
    location: "Select City Walk, Delhi",
    date: new Date("2025-07-09"),
    time: "21:00",
    category: "movies",
  },
  {
    title: "Football Match: Manchester United vs Liverpool",
    description:
      "A high-stakes Premier League match between Manchester United and Liverpool.",
    location: "Old Trafford, Manchester",
    date: new Date("2025-07-10"),
    time: "20:00",
    category: "football",
  },
  {
    title: "Cricket Exhibition Match",
    description:
      "A friendly exhibition match featuring local and international players.",
    location: "Rajiv Gandhi International Cricket Stadium, Hyderabad",
    date: new Date("2025-07-11"),
    time: "13:00",
    category: "cricket",
  },
];

for (const activity of sampleActivities2) {
  fetch("http://localhost:3000/activity/add", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(activity),
  })
    .then((res) => res.json())
    .then((data) => console.log(data));
}
